title: PHOTORAMA
email: ''
description: Photo Journal
url: ''
baseurl: ''
facebook_username: ''
twitter_username: ''
instagram_username: ''
github_username: ''
deviantart_username: ''
flickr_username: ''
discus_shortname: ''
share: true
owner:
  name: photorama
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template
comments:
  provider: disqus
  disqus:
    short_name: ''
nav:
  - GALLERY: 'https://sunbliss.github.io/photorama/gallery/'
  - JOURNAL: 'https://sunbliss.github.io/photorama/journal/'
  - ABOUT: 'https://sunbliss.github.io/photorama/about/'
translations:
  permalink: /404.html
destination: ./_site
port: 4000
markdown: kramdown
highlighter: rouge
permalink: '/journal/:title/'
paginate: 5
paginate_path: '/journal/page:num/'
categories_path: /journal/category/
tags_path: /journal/tag/
gems:
  - jekyll-paginate
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
sitemap:
  file: /sitemap.xml
  exclude:
    - /atom.xml
    - /feed.xml
    - /feed/index.xml
  include_posts:
    - /writing/
  change_frequency_name: change_frequency
  priority_name: priority
